config/routes.rb
Rails.application.routes.draw do
  resources :listings

  resources :charges

  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'pages/contact'

  get 'dashboard' => 'pages#dashboard'

  get 'start' => 'listings#listing'

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  time       :string(255)
#  date       :string(255)
#  seats      :integer
#  venue_name :string(255)
#  location   :text
#  other_info :text
#  projector  :boolean          default(FALSE)
#  cables     :boolean          default(FALSE)
#  laptops    :boolean          default(FALSE)
#  seating    :boolean          default(FALSE)
#  blinds     :boolean          default(FALSE)
#  lighting   :boolean          default(FALSE)
#  camcorder  :boolean          default(FALSE)
#  catering   :boolean          default(FALSE)
#  toilets    :boolean          default(FALSE)
#  fire       :boolean          default(FALSE)
#  internet   :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#  price      :decimal(, )
#  user_id    :integer
#

class Listing < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  
	belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  accepts_nested_attributes_for :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) do |u| 
  		u.permit(
  		 	:name,
  		 	:email, :password, :confirmation_password, 
	  		listings_attributes: [
	  			:title, :time, :date, :seats,
  				:venue_name, :location, :other_info,
  				:price, :projector, :cables,
  				:laptops, :seating, :blinds,
  				:lighting, :camcorder, :catering,
  				:toilets, :fire, :internet, :image
	  		]
	  	)
	  end 
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Open Cinema customer',
    :currency    => 'gbp'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to charges_path
end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  respond_to :html
  def listing
    @listing = Listing.new
  end
  
  def index
    @listings = Listing.all
    respond_with(@listings)
  end

  def show
    respond_to do |format|
      format.html { respond_with(@listing) }
      format.js {}
    end
    
  end

  def new
    @listing = Listing.new
    respond_with(@listing)
  end

  def edit
  end

  def create
    @listing = current_user.listings.new(listing_params)
    @listing.save
    respond_with(@listing)
  end

  def update
    @listing.update(listing_params)
    respond_with(@listing)
  end

  def destroy
    @listing.destroy
    respond_with(@listing)
  end

  private
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:title, :time, :date, :seats, :venue_name, :location, :other_info, :projector, :cables, :laptops, :seating, :blinds, :lighting, :camcorder, :catering, :toilets, :fire, :internet, :price, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]
  def home
  	if current_user
  	redirect_to dashboard_path
  	end
  end

  def about
  end

  def contact
  end

  def dashboard
    @listings = current_user.listings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Open Cinema", root_path, class: "navbar-brand" %>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          
          
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Listings", listings_path %></li>
              <% if current_user %>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li><%= link_to "Dashboard", dashboard_path %></li> 
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>

                <% else %>

                <li><%= link_to 'Login', new_user_session_path %></li>

                <% end %>
                <li>

                </li>          
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oc05</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body>
  

<%= yield %>

</body>
</html>

app/views/listings/Parameters.html.erb
 Parameters: {"utf8"=>"✓", "listing"=>{"title"=>"TEST", "time"=>"2.30", "date"=>"", "seats"=>"", "venue_name"=>"", "image"=>"coffee.jpg", "price"=>"2.0", "location"=>"", "other_info"=>"", "projector"=>"0", "cables"=>"0", "laptops"=>"0", "seating"=>"0", "blinds"=>"1", "internet"=>"0", "lighting"=>"0", "camcorder"=>"0", "catering"=>"0", "toilets"=>"0", "fire"=>"0"}, "commit"=>"Create Listing"}


Started GET "/carrier_waves.3?utf8=%E2%9C%93&user%5Bname%5D=something&user%5Bcarrier_documents_attributes%5D%5B0%5D%5Bdoc_type%5D=type1&user%5Bcarrier_documents_attributes%5D%5B0%5D%5B_destroy%5D=false&user%5Bcarrier_documents_attributes%5D%5B0%5D%5Bid%5D=5&user%5Bcarrier_documents_attributes%5D%5B1427198123627%5D%5Bdoc_type%5D=type1&user%5Bcarrier_documents_attributes%5D%5B1427198123627%5D%5Bfile%5D=Screen+Shot+2015-03-21+at+18.24.06.png&user%5Bcarrier_documents_attributes%5D%5B1427198123627%5D%5B_destroy%5D=false&commit=Update+User" for ::1 at 2015-03-24 11:55:30 +0000
Processing by CarrierWavesController#index as 
  Parameters: {"utf8"=>"✓", "user"=>{"name"=>"something", "carrier_documents_attributes"=>{"0"=>{"doc_type"=>"type1", "_destroy"=>"false", "id"=>"5"}, "1427198123627"=>{"doc_type"=>"type1", "file"=>"Screen Shot 2015-03-21 at 18.24.06.png", "_destroy"=>"false"}}}, "commit"=>"Update User"}

app/views/listings/_form.html.erb
<%= render 'layouts/header' %>

<%= simple_form_for(@listing, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>



  <div class="form-inputs">
    <%= f.input :title, label: false, placeholder: "Movie Title", input_html: {class: "form-control"} %>
    <%= f.input :time, label: false, placeholder: "What time does your movie start?", input_html: {class: "form-control"} %>
    <%= f.input :date, label: false, placeholder: "What date", input_html: {class: "form-control"} %>
    <%= f.input :seats, label: false, placeholder: "Number of seats", input_html: {class: "form-control"} %>
    <%= f.input :venue_name, label: false, placeholder: "Name of venue", input_html: {class: "form-control"} %>
    <%= f.input :location, label: false, placeholder: "Address", input_html: {class: "form-control", rows: 5 } %>
    <%= f.input :other_info, label: false, placeholder: "Other information", input_html: {class: "form-control", rows: 5} %>
    <%= f.input :price, label: false, placeholder: "Ticket Price (£)", input_html: {class: "form-control"} %>

    <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.file_field :image %><br>
                  </div>
                </div>

    <div class="checkbox text-center">
    <p> Projector </p>
    <%= f.input :projector, required: false, label: false %>
    <p> Cable </p>
    <%= f.input :cables, required: false, label: false  %>
    <p> Laptop </p>
    <%= f.input :laptops, required: false, label: false  %>
    <p> Seating </p>
    <%= f.input :seating, required: false, label: false  %>
    <p> Blinds </p>
    <%= f.input :blinds, required: false, label: false %>
    <p> Lighting </p>
    <%= f.input :lighting, required: false, label: false %>
    <p> Camcorder </p>
    <%= f.input :camcorder, required: false, label: false %>
    <p> Catering </p>
    <%= f.input :catering, required: false, label: false %>
    <p> Toilets </p>
    <%= f.input :toilets, required: false, label: false %>
    <p> Fire alarm </p>
    <%= f.input :fire, required: false, label: false %>
    <p> Wifi/internet </p>
    <%= f.input :internet, required: false, label: false %>
    </div>
  </div>

    <%= f.button :submit, class: "btn btn-primary btn-block", data: { no_turbolink: true } %>

<% end %>


<body>
    

app/views/listings/_show.html.erb
<div class="modal-body">
            <h5><%= image_tag @listing.image_url %></h5>
            <h1><%= @listing.title %> <%= @listing.date %> @ <%= @listing.time %></h1>
            <h5>Venue Name: <%= @listing.venue_name %> || No of seats <%= @listing.seats %></h5>
            <h5>Address: <%= @listing.location %></h5>
            <h5>Ticket Price (£):<%= @listing.price %></h5>
            <h5>Venue info:<%= @listing.other_info %></h5>

        
        
      <h4 class="text-center">This Venue Has the Following Equipment</h4>
      <hr>
            <div class="row">
              <div class="col-sm-4">Toilets: <%= @listing.toilets %></div>
              <div class="col-sm-4">Fire: <%= @listing.fire %></div>
              <div class="col-sm-4">Projector: <%= @listing.projector %></div>
            </div>
            <div class="row">
              <div class="col-sm-4">Internet: <%= @listing.internet %></div>
              <div class="col-sm-4">Camcorder: <%= @listing.camcorder %></div>
              <div class="col-sm-4">Laptops: <%= @listing.laptops %></div>
            </div>
            <div class="row">
              <div class="col-sm-4">Lighting: <%= @listing.lighting %></div>
              <div class="col-sm-4">Camcorder: <%= @listing.camcorder %></div>
              <div class="col-sm-4">Catering: <%= @listing.catering %></div>
            </div>
            <div class="row">
              <div class="col-sm-4">Seating: <%= @listing.seating %></div>
              <div class="col-sm-4">Blinds: <%= @listing.blinds %></div>
            </div>
            
</div>

      

  

app/views/listings/added.html.erb
<h4></h4>
            <h4>21/03/2015 - 12:30 @ Blah</h4>
            <h5>Location name</h5>
            <p>Address... - <a href="#">Map</a></p>

            <div class="row">
              <div class="col-sm-4">Number of sits: <div class="badge">42</div></div>
              <div class="col-sm-4">Ticket price: <div class="badge">42</div></div>
              <div class="col-sm-4">Projector: <div class="badge">Yes</div></div>
            </div>
            <div class="row">
              <div class="col-sm-4">Number of sits: <div class="badge">42</div></div>
              <div class="col-sm-4">Ticket price: <div class="badge">42</div></div>
              <div class="col-sm-4">Projector: <div class="badge">Yes</div></div>
            </div>
            <div class="row">
              <div class="col-sm-4">Number of sits: <div class="badge">42</div></div>
              <div class="col-sm-4">Ticket price: <div class="badge">42</div></div>
              <div class="col-sm-4">Projector: <div class="badge">Yes</div></div>
            </div>
            <div class="row">
              <div class="col-sm-4">Number of sits: <div class="badge">42</div></div>
              <div class="col-sm-4">Ticket price: <div class="badge">42</div></div>
              <div class="col-sm-4">Projector: <div class="badge">Yes</div></div>
            </div>

app/views/listings/edit.html.erb
<h3 class="text-center">Editing listing</h3>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="center">Current Open Cinema Movies</h3>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped" id="dataTables-example">
                <thead>
                    <tr>
                        <th class="center"><h4>Movie</h4></th>
                        <th class="center"><h4>Date</h4></th>
                        <th class="center"><h4>Time</h4></th>
                        <th class="center"><h4>Location</h4></th>
                        <th class="center"><h4>Price (£)</h4></th>
                        <th class="center"><h4>Action</h4></th>
                    </tr>
                </thead>

    <% @listings.each do |listing| %>
      <tr>
        <td><p><%= listing.title %></p></td>
        <td><p><%= listing.date %></p></td>
        <td class="center"><p><%= listing.time %></p></td>
        <td class="center"><p><%= listing.location %></p></td>
        <td class="center"><p><%= listing.price %></p></td>
        
        <td>
          <%= link_to 'Buy Tickets Now', "/", class: "btn btn-success" %>
          <%= link_to 'View More Info', listing_path(listing), remote: true, id: 'showButton', class: 'btn btn-primary' %>
        </td>
        
      </tr>
    <% end %>
</table>

    <div class="panel-heading">
        <h3 class="center"><%= link_to 'Back', "/", class: "btn btn-lg btn-success" %></h3>
    </div>

<br>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Movie Information</h4>
               <hr>
          </div>
          <div class="modal-body" id="modelContent">
            
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-success">Buy Tickets Now</button>
          </div>
        </div>
      </div>
    </div>


    

app/views/listings/listing.html.erb
<div class="jumbotron1">

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <!--      Wizard container   :html => { multipart: true })      -->   
      <div class="wizard-container"> 
        <%= simple_form_for(@listing, url: new_user_registration_path, method: :get,  :html => { multipart: true } ) do |f| %>

          <div class="card wizard-card ct-wizard-orange" id="wizard">
            <!--        You can switch "ct-wizard-orange"  with one of the next bright colors: "ct-wizard-blue", "ct-wizard-green", "ct-wizard-orange", "ct-wizard-red"             -->

            <div class="wizard-header">
              <h3>
                <b>LIST</b> YOUR MOVIE <br>
                <small>This information will let us know more about your movie</small>
              </h3>
            </div>

            <ul>
              <li><a href="#about" data-toggle="tab">Movie Information</a></li>
              <li><a href="#account" data-toggle="tab">Location</a></li>
              <li><a href="#address" data-toggle="tab">Equipment</a></li>
            </ul>
          
            <div class="tab-content">

              <!-- panel 1 -->
              <div class="tab-pane" id="about">
                <div class="row">
                  <div class="col-sm-12">
                    <h4 class="info-text">Let's start with the basic information</h4>
                  </div>
                </div>          
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :title, placeholder: "E.g. Top Gun", input_html: {class: "form-control"} %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :time, placeholder: "E.g. 2.30pm", input_html: {class: "form-control"} %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :date, placeholder: "E.g. 19/03/2015", input_html: {class: "form-control"} %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :seats, placeholder: "E.g. 5,10,15,20", input_html: {class: "form-control"} %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :venue_name, placeholder: "Give your venue a name upload image", input_html: {class: "form-control"} %>
                  </div>
                </div>

    <!------ IMAGE FIELD ------>

                 <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.file_field :image %><br>
                  </div>
                </div>


                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :price, placeholder: "£", input_html: {class: "form-control"} %>
                  </div>
                </div>
              </div>

              <!-- panel 2 -->
              <div class="tab-pane" id="account">
                <div class="row">
                  <div class="col-sm-12">
                    <h4 class="info-text"> Give Us Some Information About Your Movie </h4>
                  </div>
                </div>          
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :location, placeholder: "Full Address including postcode", input_html: {class: "form-control"} %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.input :other_info, placeholder: "Any other information about the venue", input_html: {class: "form-control"} %>
                  </div>
                </div>
              </div>

              <!-- panel 3 -->
              <div class="tab-pane" id="address">
                <div class="row">
                  <div class="col-sm-12">
                    <h4 class="info-text"> Do You Have the Following Equipment </h4>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-3 col-sm-offset-1">
                    <%= f.input :projector, required: false %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :cables, required: false  %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :laptops, required: false  %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-3 col-sm-offset-1">
                    <%= f.input :seating, required: false  %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :blinds, required: false %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :internet, required: false %>
                  </div>
                  
                </div>
                <div class="row">
                  <div class="col-sm-3 col-sm-offset-1">
                    <%= f.input :lighting, required: false %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :camcorder, required: false %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :catering, required: false %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-3 col-sm-offset-1">
                    <%= f.input :toilets, required: false %>
                  </div>
                  <div class="col-sm-4">
                    <%= f.input :fire, required: false %>
                  </div>
                  
                </div>


              </div>
            </div>
            <div class="wizard-footer">
              <div class="pull-right">
                <input type='button' class='btn btn-next btn-fill btn-warning btn-wd btn-sm' name='next' value='Next' />
                <%= f.button :submit, class: "btn btn-finish btn-fill btn-warning btn-wd btn-sm" %>
              </div>
              <div class="pull-left">
                <input type='button' class='btn btn-previous btn-fill btn-default btn-wd btn-sm' name='previous' value='Previous' />
              </div>
              <div class="clearfix"></div>
            </div>  
          </div>
        <% end %>
      </div> <!-- wizard container -->
    </div>
  </div><!-- end row -->
</div>
</div>

app/views/listings/new.html.erb
<h3 class="text-center">New listing</h3>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<%= render 'layouts/header' %>

<%= render 'show' %>

app/views/listings/show.js.erb
$('#modelContent').html('<%= j render 'show' %>');
$('#modal1').modal('show');

app/views/pages/contact.html.erb
 <%= render 'layouts/header' %>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/dashboard.html.erb
 <%= render 'layouts/header' %>
                
            <div class="row">
                <div class="col-lg-12">
                    <h5 class="center">Dashboard <%= link_to "Create New Cinema", new_listing_path, class: "btn btn-danger" %></h5>
                  
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
         
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h5 class="center">My Current Movie Listings</h5>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Movie</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Seats</th>
                                            <th>Venue Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @listings.each do |listing| %>
        <tr>
          <td><%= link_to listing.title, listing_path(listing) %></td>
          <td><%= listing.date %></td>
          <td><%= listing.time %></td>
          <td><%= listing.seats %></td>
          <td><%= listing.venue_name %></td>
          
          <td><%= link_to "Edit Movie", edit_listing_path(listing) %></td>
          
        </tr>
        <% end %>
      </tbody>
</table>  
                                    
                            <!-- /.table-responsive -->
        <div class="well">
            <h4>OPEN CINEMA INFORMATION</h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. <a target="_blank" href="https://opencinema.net/">https://opencinema.net/</a>.</p>
            <a class="btn btn-default btn-lg btn-block" target="_blank" href="https://opencinema.net/">View OpenCinema Documentation</a>
        </div>


                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <h5 class="center">Purchase Information</h5>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Movie</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Seats</th>
                                            <th>Venue Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @listings.each do |listing| %>
        <tr>
          <td><%= link_to listing.title, listing_path(listing) %></td>
          <td><%= listing.date %></td>
          <td><%= listing.time %></td>
          <td><%= listing.seats %></td>
          <td><%= listing.venue_name %></td>
          
          <td><%= link_to "Edit Movie", edit_listing_path(listing) %></td>
          
        </tr>
        <% end %>
      </tbody>
</table>  

<div class="well">
            <h4>OPEN CINEMA INFORMATION</h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. <a target="_blank" href="https://opencinema.net/">https://opencinema.net/</a>.</p>
            <a class="btn btn-default btn-lg btn-block" target="_blank" href="https://opencinema.net/">View OpenCinema Documentation</a>
        </div>


                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h5 class="center">Sales Information</h5>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Movie</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Seats</th>
                                            <th>Venue Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @listings.each do |listing| %>
        <tr>
          <td><%= link_to listing.title, listing_path(listing) %></td>
          <td><%= listing.date %></td>
          <td><%= listing.time %></td>
          <td><%= listing.seats %></td>
          <td><%= listing.venue_name %></td>
          
          <td><%= link_to "Edit Movie", edit_listing_path(listing) %></td>
          
        </tr>
        <% end %>
      </tbody>
</table>  

 
    <!-- /.panel-body -->

<!-- /.panel -->

           
    
         
     


    

app/views/pages/home.html.erb
<div class="jumbotron">
	<ul class="nav pull-right">
		<%= link_to 'Login', new_user_session_path, class: "btn btn-sm" %>
		<%= link_to 'About', about_path, class: "btn btn-sm" %>
	</ul>

  	
      <div class="container">
      	<div class="center">
      	<h1>Open Cinema</h1>
      	<h2>The Easiest Way to Create Your Own Cinema</h2> 
      	<%= link_to "Get Started Today ", start_path ,class: "btn btn-success btn-xlarge", data: { no_turbolink: true } %>
      	<%= link_to "View Current Listings", listings_path ,class: "btn btn-danger btn-xlarge" %>
      </div>
</div>
</div>


 